FROM chrisns/scrumonline

RUN apt-get update && \
  apt-get install -y mysql-server && \
  apt-get clean

COPY mysql.cnf /etc/mysql/conf.d/mysql-hack.cnf

RUN ./mysql_init.sh

CMD mysqld_safe & apache2-foreground

