name: Docker Image CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - name: Build ${GITHUB_REPOSITORY}:latest
        run: docker build -t ${GITHUB_REPOSITORY}:latest .

      - name: Build ${GITHUB_REPOSITORY}:bundled
        run: docker build -t ${GITHUB_REPOSITORY}:bundled -f Dockerfile.mysql .

      - name: Docker login
        if: github.ref == 'refs/heads/master'
        env:
          docker_username: ${{ secrets.docker_username }}
          docker_password: ${{ secrets.docker_password }}
        run: docker login  -u $docker_username -p ${docker_password}

      - name: Docker Tags
        run: |
          docker tag ${GITHUB_REPOSITORY}:latest ${GITHUB_REPOSITORY}:latest-${GITHUB_SHA}
          docker tag ${GITHUB_REPOSITORY}:bundled ${GITHUB_REPOSITORY}:bundled-${GITHUB_SHA}

      - name: Push ${GITHUB_REPOSITORY}:latest
        if: github.ref == 'refs/heads/master'
        run: |
          docker push ${GITHUB_REPOSITORY}:latest
          docker push ${GITHUB_REPOSITORY}:latest-${GITHUB_SHA}

      - name: Push ${GITHUB_REPOSITORY}:bundled
        if: github.ref == 'refs/heads/master'
        run: |
          docker push ${GITHUB_REPOSITORY}:bundled
          docker push ${GITHUB_REPOSITORY}:bundled-${GITHUB_SHA}
